### ISSUE TITLE
Use AssertionError instead of VerificationError?

### ISSUE THREAD

**Issue by sumnerevans** [jackrosenthal/algobowl#1]
AssertionError is a bulitin exception type, and can make the writing of verifiers easier (also, no need for weird shenanigans with importing VerificationError from the module).

For verifiers, you could just do something like:

```
assert <the condition>, "The message"
```

which is a lot more readable than the current system.

I can make the change, just wanted to get this approved before doing so.

EDIT:

- Pasting this here for my own reference when I get around to implementing this: https://stackoverflow.com/questions/2380073/how-to-identify-what-function-call-raise-an-exception-in-python

**Comment by jackrosenthal** [comment]
The concern to me would be that runtime errors could accidentally be counted against the student. For example, if the verifier called a library routine with invalid arguments and an assertion was raised (yes, not the right exception type for invalid arguments, but unfortunately even some procedures in the Python standard library behave this way...).

We could get around this by doing some shenanigans with the exception object and making sure the ``AssertionError`` was raised from the verifier module. If you want to tackle that, have at it. I just thought ``VerificationError`` was the far easier way to do this.

**Comment by jackrosenthal** [comment]
... to add to the above. The above case is rather unlikely. If you wanted to start out with a change which did not do this check, file a bug, then we tackle it later, it seems like a reasonable iterative development process to me.

Or if you just want to do the whole thing at once, have at it. Up to you.

**Comment by jackrosenthal** [comment]
Closing this as obsolete since the new problem format changed significantly how verifiers are written.  Internally, `VerificationError` and `FileFormatError` are still used, but much of this gets abstracted away by `problemlib` helpers, and it doesn't taste too bad.
