### ISSUE TITLE
Server Error During "Verification"

### ISSUE THREAD

**Issue by lillysline** [jackrosenthal/algobowl#10]
Starting at 10:00 PM, at the conclusion of "Output Upload" and the beginning of "Verification", when going to the algobowl website and attempting to access mines.algobowl.org/group/<groupNumber>, the algobowl website displays a 500 server error, with the following text

> Error 500
> 
> We're sorry but we weren't able to process this request.
> 
> If you've reached this page through a normal sequence of actions, please [submit a bug](https://github.com/jackrosenthal/algobowl/issues).

The issue has persisted for 10 minutes so far (10:10 PM).

**Comment by jackrosenthal** [comment]
fixed in 5bd2ef17f9855e1dc6f2257838f47e18e57a7295
