### ISSUE TITLE
Ensure that AssertionError comes from the verification module

### ISSUE THREAD

**Issue by sumnerevans** [jackrosenthal/algobowl#9]
Followup to #1

Currently, if an `AssertionError` occurs in a module that is called by the verification module (and not subsequently handled by the verification modulet, AlgoBOWL will think that it's a verifier error and show it to the user.

* https://github.com/jackrosenthal/algobowl/issues/1#issuecomment-464865715

# Potential Solutions:
* https://stackoverflow.com/questions/2380073/how-to-identify-what-function-call-raise-an-exception-in-python
* https://stackoverflow.com/a/22232202/2319844

**Comment by jackrosenthal** [comment]
likely not needed anymore with the new problem format
